# Generated by Django 6.0.5 on 2026-05-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ketersediaan_energi', models.IntegerField()),
                ('keterjangkauan_energi', models.IntegerField()),
                ('keberlanjutan_energi', models.IntegerField()),
                ('keandalan_energi', models.IntegerField()),
                ('esi_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelapor', models.CharField(max_length=100)),
                ('kategori_laporan', models.CharField(choices=[('Gangguan Listrik', 'Gangguan Listrik'), ('Akses Energi Terbatas', 'Akses Energi Terbatas'), ('Biaya Energi Mahal', 'Biaya Energi Mahal'), ('Energi Terbarukan', 'Energi Terbarukan'), ('Lainnya', 'Lainnya')], max_length=100)),
                ('isi_laporan', models.TextField()),
                ('status', models.CharField(choices=[('Baru', 'Baru'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Baru', max_length=50)),
                ('tanggal_laporan', models.DateTimeField(auto_now_add=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_warga', to='energi.desa')),
            ],
        ),
    ]
